config/routes.rb
Rails.application.routes.draw do
  get 'hello/index'

  root 'hello#index'

  resources :articles
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article

		else
			render 'new'
		end	
	end

	def show
		@article = Article.find(params[:id])
	end

	def index
		@articles = Article.all
	end

	 def edit 
	@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to article_path
	end


	private
		def article_params
			params.require(:article).permit(:title, :text)
		end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_for :article, url: article_path(@article), method: :path do |f| %>

	<% if @article.errors.any? %>
		<div id="error_explanation">
		</div>
			<h2>
				<%= pluralize(@article.errors.count, "error") %> proibited this article from being saved:
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end%>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>


app/views/articles/index.html.erb
<h1> Listing Articles </h1>

<table>
<tr>
<th> Title</th>
<th> Text</th>
</tr>

<% @articles.each do |article| %>
<tr>
<td> <%= article.title %> </td>
<td> <%= article.text %> </td>
<td> <%= link_to 'Show', article_path(article) %> </td>
<td> <%= link_to 'Edit', edit_article_path(article) %> </td>
<td> <%= link_to 'Delete', articles_path, method: :delete, data: {confirm: 'Are you sure?'} %> </td>
</tr>
<% end %>	
</table>

<%= link_to 'New', new_article_path %> <br>
<br>

<%= link_to 'Back', hello_index_path %>






app/views/articles/new.html.erb
<h1>Novo Artigo :D</h1>

<%= form_for :article, url: articles_path do |f| %>
	<% if @article.errors.any? %>
		<div id="error_explanation"
			<h2>
			<%= pluralize(@article.errors.count, "error") %> prohibited this article for being saved
			</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	<p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>


<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>strong>
	<%= @article.title %>
</p>

<p>
	<strong>Text:</strong>
	<%= @article.title %>
</p>
<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>

<p>
	<strong>Text:</strong>
	<%= @article.title %>
</p>

<%= link_to 'Back', articles_path %>


app/views/hello/index.html.erb
<h1>Blog da Thali</h1>
<%= link_to 'Meu Blog', controller: 'articles' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>